### PR TITLE
Spec breaking on invalid uris

### PR DESCRIPTION
**Pull request by kwkwan**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Can we not change the XMI file?Because that is what the user exports directly, we can't ask them to change those namespaces to match.

**Comment by kwkwan** [comment]
Yes, but we need to create xmi models with namespace XML 20110701 and UML 20110701.  Since Shale models will verify the url of the namespaces.

**Comment by ronaldtse** [comment]
That means we should support the older export formats? If we don't support the older formats, we need to state which formats are supported, and we should also re-export this XMI file using a newer version instead of manually changing the XML.

**Comment by opoudjis** [comment]
I don't have an opinion here, but these solutions in general do need to err on the side of tolerance of data...

**Comment by ronaldtse** [comment]
@kwkwan is this to be merged? If so please merge it, thanks.

**Comment by kwkwan** [comment]
> @kwkwan is this to be merged? If so please merge it, thanks.

Ok.  Got it.

**Pull request merged**
